tests_include:
#  - minimum-time-v1
#  - minimum-time-v2
#  - minimum-time-v3
  - domain-name
#  - services
#  - telnet
#  - name-servers-present
#  - name-servers-absent
#  - name-servers
#  - lldp


# double-check if "set login system retry-options minimum-time 40" is configured:
minimum-time-v1:
  - rpc: get-config
  - item:
      xpath: //configuration/system/login/retry-options
      tests:
        - is-equal: minimum-time, 40
          info: "Test Succeeded!!, minimum-time is equal to <{{post['minimum-time']}}>"
          err: "Test Failed!!!, minimum-time is not equal to 40, it is <{{post['minimum-time']}}>"

# double-check if "set login system retry-options minimum-time 40" is configured:
minimum-time-v2:
  - rpc: get-config
  - kwargs:
      filter_xml: configuration/system/login/retry-options
  - item:
      xpath: //login/retry-options
      tests:
        - is-equal: //minimum-time, 40
          info: "Test Succeeded!!, minimum-time is equal to <{{post['minimum-time']}}>"
          err: "Test Failed!!!, minimum-time is not equal to 40, it is <{{post['minimum-time']}}>"

# double-check if "set login system retry-options minimum-time 40" is configured:
minimum-time-v3:
  - rpc: get-config
  - kwargs:
      filter_xml: configuration/system/login
  - item:
      xpath: //retry-options
      tests:
        - is-equal: //minimum-time, 40
          info: "Test Succeeded!!, minimum-time is equal to <{{post['//minimum-time']}}>"
          err: "Test Failed!!!, minimum-time is not equal to 40, it is <{{post['//minimum-time']}}>"

# double-check if domain name is configured properly
domain-name:
  - command: show configuration system domain-name | display xml
  - item:
      xpath: //configuration/system
      tests:
        - contains: domain-name, jnpr.net
          err: "Test Failed!! domain-name contains doesnt jnpr.net. it is <{{post['domain-name']}}>"
          info: "Test succeeded!! domain-name contains jnpr.net. it is <{{post['domain-name']}}>"
        - is-equal: //domain-name, poc-nl.jnpr.net
          err: "Test Failed!! domain-name is not poc-nl.jnpr.net. it is <{{post['domain-name']}}>"
          info: "Test succeeded!! domain-name is <{{post['domain-name']}}>"

# double-check if telnet service is configured, and if ftp service is not configured
services:
  - command: show configuration system | display xml
  - iterate:
      xpath: system/services
      tests:
        - exists: telnet
          err: "Test Failed!! telnet is not configured"
          info: "Test succeeded!! telnet is configured"
        - not-exists: ftp
          err: "Test Failed!! ftp is configured"
          info: "Test succeeded!! ftp is not configured"

# double-check if telnet service is configured
telnet:
  - command: show configuration system services
  - iterate:
      xpath: //configuration-information
      tests:
        - contains: configuration-output, telnet
          err: "Test Failed!! telnet is not configured"
          info: "Test succeeded!! telnet is configured"


# check if dns 8.8.8.8 and 8.8.4.4 are configured
name-servers-present:
  - command: show configuration system name-server
  - iterate:
      xpath: //configuration-information
      tests:
        - contains: configuration-output, 8.8.8.8
          err: "Test Failed!! name-server 8.8.8.8 is not configured"
          info: "Test succeeded!! name-server 8.8.8.8 is configured"
        - contains: configuration-output, 8.8.4.4
          err: "Test Failed!! name-server 8.8.4.4 is not configured"
          info: "Test succeeded!! name-server 8.8.4.4 is configured"

# check if dns 172.30.179.144 is not configured
name-servers-absent:
  - command: show configuration system | display xml
  - iterate:
      xpath: /configuration/system/name-server
      tests:
        - not-equal: name, 172.30.179.144
          err: "Test Failed!! name-server <{{post['name']}}> is configured"
          info: "Test succeeded!! name-server configured is <{{post['name']}}>. It is not 172.30.179.44"

# check if dns 8.8.8.8 and 8.8.4.4 are configured, and check if dns 172.30.179.144 is not configured
name-servers:
  - rpc: get-config
  - kwargs:
      filter_xml: configuration/system/name-server
  - item:
      xpath: //configuration/system/name-server[normalize-space(name) = "8.8.8.8"]
      tests:
        - exists: name 
          info: "Test Succeeded !!. The name server <{{post['name']}}> is configured."
          err: "Test Failed !!. The name server <{{post['name']}}> is not configured."
  - item:
      xpath: //configuration/system/name-server[normalize-space(name) = "8.8.4.4"]
      tests:
        - exists: name 
          info: "Test Succeeded !!. The name server <{{post['name']}}> is configured."
          err: "Test Failed !!. The name server is <{{post['name']}}> not configured."
  - item:
      xpath: //configuration/system/name-server[normalize-space(name) = "172.30.179.144"]
      tests:
        - not-exists: name 
          info: "Test Succeeded !! The name server 172.30.179.144 is not configured"
          err: "Test Failed !!. The name server 172.30.179.144 is configured"
          ignore-null: True

lldp:
  - rpc: get-config
  - kwargs:
      filter_xml: configuration/protocols/lldp
  - item:
      xpath: //configuration/protocols/lldp/interface[normalize-space(name) = "ge-0/0/0"]
      tests:
        - exists: name 
          info: "Test Succeeded !! lldp is configured for interface <{{post['name']}}> ."
          err: "Test Failed !! lldp is not configured for interface <{{post['name']}}>"
  - item:
      xpath: //configuration/protocols/lldp/interface[normalize-space(name) = "ge-0/0/1"]
      tests:
        - exists: name 
          info: "Test Succeeded !! lldp is configured for interface <{{post['name']}}>."
          err: "Test Failed !! lldp is not configured for interface <{{post['name']}}>."
